package models

var (
	AllMetrics = [...]*Metric{
		{"Alloc", GaugeType, 0, 0, RuntimeSource, ""},
		{"BuckHashSys", GaugeType, 0, 0, RuntimeSource, ""},
		{"Frees", GaugeType, 0, 0, RuntimeSource, ""},
		{"GCCPUFraction", GaugeType, 0, 0, RuntimeSource, ""},
		{"GCSys", GaugeType, 0, 0, RuntimeSource, ""},
		{"HeapAlloc", GaugeType, 0, 0, RuntimeSource, ""},
		{"HeapIdle", GaugeType, 0, 0, RuntimeSource, ""},
		{"HeapInuse", GaugeType, 0, 0, RuntimeSource, ""},
		{"HeapObjects", GaugeType, 0, 0, RuntimeSource, ""},
		{"HeapReleased", GaugeType, 0, 0, RuntimeSource, ""},
		{"HeapSys", GaugeType, 0, 0, RuntimeSource, ""},
		{"LastGC", GaugeType, 0, 0, RuntimeSource, ""},
		{"Lookups", GaugeType, 0, 0, RuntimeSource, ""},
		{"Lookups", GaugeType, 0, 0, RuntimeSource, ""},
		{"MCacheInuse", GaugeType, 0, 0, RuntimeSource, ""},
		{"MCacheSys", GaugeType, 0, 0, RuntimeSource, ""},
		{"MSpanInuse", GaugeType, 0, 0, RuntimeSource, ""},
		{"MSpanSys", GaugeType, 0, 0, RuntimeSource, ""},
		{"Mallocs", GaugeType, 0, 0, RuntimeSource, ""},
		{"NextGC", GaugeType, 0, 0, RuntimeSource, ""},
		{"NumForcedGC", GaugeType, 0, 0, RuntimeSource, ""},
		{"NumGC", GaugeType, 0, 0, RuntimeSource, ""},
		{"OtherSys", GaugeType, 0, 0, RuntimeSource, ""},
		{"PauseTotalNs", GaugeType, 0, 0, RuntimeSource, ""},
		{"StackInuse", GaugeType, 0, 0, RuntimeSource, ""},
		{"StackSys", GaugeType, 0, 0, RuntimeSource, ""},
		{"Sys", GaugeType, 0, 0, RuntimeSource, ""},
		{"TotalAlloc", GaugeType, 0, 0, RuntimeSource, ""},
		{"PollCount", CounterType, 0, 0, CounterSource, ""},
		{"RandomValue", GaugeType, 0, 0, RandomSource, ""},
		{"TotalMemory", GaugeType, 0, 0, GopsutilSource, ""},
		{"FreeMemory", GaugeType, 0, 0, GopsutilSource, ""},
		{"CPUutilization", GaugeType, 0, 0, GopsutilSource, ""},
	}
)
